<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>牛逼代码发布 by wangguan</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="超级牛逼的代码发布平台">
    <meta name="author" content="wangguan">

    <!-- Le styles -->
    <link href="/http/static/css/bootstrap.min.css" rel="stylesheet">
    <style type="text/css">
      body {
        padding-top: 40px;
        padding-bottom: 40px;
        background-color: #f5f5f5;
      }

      .form-signin {
        max-width: 300px;
        padding: 19px 29px 29px;
        margin: 0 auto 20px;
        background-color: #fff;
        border: 1px solid #e5e5e5;
        -webkit-border-radius: 5px;
           -moz-border-radius: 5px;
                border-radius: 5px;
        -webkit-box-shadow: 0 1px 2px rgba(0,0,0,.05);
           -moz-box-shadow: 0 1px 2px rgba(0,0,0,.05);
                box-shadow: 0 1px 2px rgba(0,0,0,.05);
      }
      .form-signin .form-signin-heading,
      .form-signin .checkbox {
        margin-bottom: 10px;
      }
      .form-signin input[type="text"],
      .form-signin input[type="password"] {
        font-size: 16px;
        height: auto;
        margin-bottom: 15px;
        padding: 7px 9px;
      }

    </style>
    <link href="/http/static/css/bootstrap-responsive.min.css" rel="stylesheet">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="../assets/js/html5shiv.js"></script>
    <![endif]-->

    <!-- Fav and touch icons -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="../assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../assets/ico/apple-touch-icon-114-precomposed.png">
      <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../assets/ico/apple-touch-icon-72-precomposed.png">
                    <link rel="apple-touch-icon-precomposed" href="../assets/ico/apple-touch-icon-57-precomposed.png">
                                   <link rel="shortcut icon" href="../assets/ico/favicon.png">
  </head>

  <body>

    <div class="container">
		<h1 class="form-signin-heading">牛逼的代码发布平台</h1>
		<form class="form-signin" action='/login' method="POST">
        <h2 class="form-signin-heading">Please Login</h2>
		<h3 class="form-signin-heading" style="color:red"><?=$error_msg;?></h3>
        <input type="text" class="input-block-level" placeholder="Username" name="username" value="<?=$username;?>">
        <input type="password" class="input-block-level" placeholder="Password" name="password">
        <button class="btn btn-large btn-primary" type="submit">Login</button>
      </form>
    </div> <!-- /container -->
	<div id="footer">
      <div class="container">
		  <p class="muted credit"> Copyrigh 2015 by ruanyun</p>
      </div>
    </div>
  </body>
</html>
