<html>
    <head>
        <meta http-equiv="content-type" content="text/html; charset=UTF-8">
        <title>牛逼的代码发布平台</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="wangguan">
        <link href="/http/static/css/bootstrap.min.css" rel="stylesheet">
        <style>
			body {
				padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
			}
        </style>
        <link href="/http/static/css/bootstrap-responsive.min.css" rel="stylesheet">
    </head>

    <body>


        <div class="navbar navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <h1><a class="brand" href="/">牛逼代码发布平台</a></h1>
					<div class="nav pull-left">
                        <div>
							<ul class="nav">
								<li class="<?php if ($env == 'test'){ echo 'active';}?>"><a href="/pub?env=test">test分支切换</a></li>
								<li class="<?php if ($env == 'sanbox'){ echo 'active';}?>"><a href="/pub?env=sanbox">sanbox分支切换</a></li>
								<li class="<?php if ($env == 'online'){ echo 'active';}?>"><a href="/pub?env=online">发布线上代码</a></li>
							</ul>
                        </div>
                    </div>
					
                    <div class="nav pull-right">
                        <div id="login_user">
							<ul class="nav">
								<li><a href="/outlogin">退出</a></li>
							</ul>
							
                            <!--
                                <a href="/login_to_weibo">登陆</a>
                            -->
                        </div>
                    </div>
                    <div class="topnav">
                    </div>
                </div>
            </div>
        </div>
		<div class="container">
			<?php if ($error_msg == ''){ ?>
			<table class="table table-bordered">
				<caption><h2>好人一生平安</h2></caption>
				<thead>
					<tr>
						<th>项目名</th>
						<th>域名</th>
						<th>操作</th>
					</tr>
				</thead>
				<tbody>
					<?php foreach ($project_info as $key => $value) { ?>
						<tr>
							<td><?=$value['name']?></td>
							<td><?=$value['domain']?></td>
							<td><a href="/detail?env=<?=$env?>&project=<?=$key?>">发布</a></td>
						</tr>
					<?php }?>
					
				</tbody>
			</table>
			<?php } else { ?>
			<h2 style="color: red">您没有权限！</h2>
			<?php } ?>
		</div><!--/.fluid-container-->
	<div id="footer">
      <div class="container">
		  <p class="muted credit"> Copyrigh 2015 by ruanyun</p>
      </div>
    </div>
    </body>
</html>
